#!/usr/bin/env python3
"""Bake js/world-map-data.js (Phần 3 "Ý nghĩa quốc tế" map) from Natural Earth 1:50m countries.

    python3 tools/build-world.py ne_50m_admin_0_countries.geojson

Same projection family as tools/build-map.py (equirectangular scaled by cos of a mid latitude), framed on
Africa → Asia → Japan. Reuses its simplify/clip helpers and the same South China Sea rule: islets held under
other countries' polygons are dropped, Hoàng Sa / Trường Sa are hand-placed as Vietnamese dots.
"""
import importlib.util
import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("build_map", HERE / "build-map.py")
bm = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bm)

LON0, LON1, LAT0, LAT1 = 0.0, 160.0, -40.0, 60.0
K = math.cos(math.radians(22.0))
S = 1600 / ((LON1 - LON0) * K)
W, H = 1600, round((LAT1 - LAT0) * S)


def proj(lon, lat):
    return ((lon - LON0) * K * S, (LAT1 - lat) * S)


def ring_area(pts):
    return abs(sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(pts, pts[1:] + pts[:1]))) / 2


def main(src):
    data = json.loads(Path(src).read_text())
    vn, land = [], []
    pad = 30
    for f in data["features"]:
        iso = f["properties"].get("ADM0_A3")
        for ring in bm.rings_of(f):
            lons = [c[0] for c in ring]
            lats = [c[1] for c in ring]
            mlon, mlat = sum(lons) / len(lons), sum(lats) / len(lats)
            if iso != "VNM" and 109.0 < mlon < 118.5 and 7.0 < mlat < 18.0:
                continue
            if iso == "CHN" and mlat < 18.0:
                continue
            pts = [proj(lon, lat) for lon, lat in ring]
            if iso == "VNM":
                pts = bm.simplify_ring(pts, 0.25)
                if len(pts) >= 3:
                    vn.append(pts)
                continue
            if max(lons) < LON0 - 5 or min(lons) > LON1 + 5 or max(lats) < LAT0 - 5 or min(lats) > LAT1 + 5:
                continue
            pts = bm.clip(bm.simplify_ring(pts, 1.5), -pad, -pad, W + pad, H + pad)
            if len(pts) >= 3 and ring_area(pts) > 14:
                land.append(pts)

    def dots(items):
        return [[round(v, 1) for v in proj(lon, lat)] for lon, lat in items]

    out = {
        "w": W,
        "h": H,
        "box": [LON0, LAT0, LON1, LAT1, round(K * S, 4), round(S, 4)],
        "land": bm.path(land),
        "vn": bm.path(vn),
        "isl": dots([(112.0, 16.5), (111.4, 16.0), (112.6, 16.8), (114.3, 10.4), (112.9, 9.0), (114.4, 11.4), (115.6, 9.9)]),
    }
    dst = HERE.parent / "js" / "world-map-data.js"
    dst.write_text(
        "/* Generated by tools/build-world.py — Natural Earth 1:50m (public domain) + hand-placed islands. */\n"
        f"window.HisWorldData = {json.dumps(out, ensure_ascii=False, separators=(',', ':'))};\n"
    )
    print(f"{dst}  {dst.stat().st_size} bytes  land rings {len(land)}  vn rings {len(vn)}  {W}x{H}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "ne_50m_admin_0_countries.geojson")
