#!/usr/bin/env python3
"""Vendor Be Vietnam Pro + Literata (from Fontsource on npm) into fonts/ and write css/fonts.css.

Run once (needs internet):  python3 tools/fetch-fonts.py
Only the vietnamese / latin-ext / latin subsets are kept, woff2 only.
"""
import io
import json
import re
import shutil
import ssl
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "fonts"
CSS_OUT = ROOT / "css" / "fonts.css"
# (npm package, family name to emit, css files to pull — first existing alternative wins)
PACKAGES = [
    ("@fontsource/be-vietnam-pro", "Be Vietnam Pro", [
        ["400.css"], ["400-italic.css"], ["500.css"], ["600.css"], ["700.css"],
    ]),
    ("@fontsource-variable/literata", "Literata", [
        ["opsz.css", "full.css", "wght.css", "index.css"],
        ["opsz-italic.css", "full-italic.css", "wght-italic.css"],
    ]),
]

FACE_RE = re.compile(r"@font-face\s*\{[^}]*\}")
WOFF2_RE = re.compile(r"url\(\s*['\"]?([^)'\"]+\.woff2)['\"]?\s*\)")
SUBSET_RE = re.compile(r"-(vietnamese|latin-ext|latin)-(?:\d{3}|wght|opsz|full|standard)-(?:normal|italic)\.woff2$")


def ssl_context():
    # python.org builds on macOS ship without CA certs unless "Install Certificates.command" was run
    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        pass
    if Path("/etc/ssl/cert.pem").exists():
        return ssl.create_default_context(cafile="/etc/ssl/cert.pem")
    return ssl.create_default_context()


SSL_CTX = ssl_context()


def fetch_package(name):
    meta_url = f"https://registry.npmjs.org/{name.replace('/', '%2F')}/latest"
    with urllib.request.urlopen(meta_url, context=SSL_CTX) as r:
        meta = json.load(r)
    with urllib.request.urlopen(meta["dist"]["tarball"], context=SSL_CTX) as r:
        data = r.read()
    return meta["version"], tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")


def read_member(tar, path):
    try:
        f = tar.extractfile(f"package/{path}")
    except KeyError:
        return None
    return f.read() if f else None


def main():
    if FONTS_DIR.exists():
        shutil.rmtree(FONTS_DIR)
    FONTS_DIR.mkdir(parents=True)

    out = ["/* Generated by tools/fetch-fonts.py — do not edit by hand. */"]
    for pkg, family, css_groups in PACKAGES:
        version, tar = fetch_package(pkg)
        out.append(f"\n/* {pkg}@{version} */")
        for alternatives in css_groups:
            css = None
            for candidate in alternatives:
                raw = read_member(tar, candidate)
                if raw:
                    css = raw.decode("utf-8")
                    break
            if css is None:
                raise SystemExit(f"{pkg}: none of {alternatives} found")
            for face in FACE_RE.findall(css):
                m = WOFF2_RE.search(face)
                if not m:
                    continue
                file_name = Path(m.group(1)).name
                if not SUBSET_RE.search(file_name):
                    continue
                font = read_member(tar, f"files/{file_name}")
                if font is None:
                    raise SystemExit(f"{pkg}: missing files/{file_name}")
                (FONTS_DIR / file_name).write_bytes(font)
                face = re.sub(r"font-family:[^;]+;", f"font-family: '{family}';", face)
                face = re.sub(r"src:[^;]+;", f"src: url('../fonts/{file_name}') format('woff2');", face)
                out.append(face)

    CSS_OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    files = sorted(p.name for p in FONTS_DIR.iterdir())
    size = sum((FONTS_DIR / f).stat().st_size for f in files)
    print(f"wrote {CSS_OUT.relative_to(ROOT)} · {len(files)} files · {size / 1024:.0f} KB in fonts/")


if __name__ == "__main__":
    main()
